'use strict';
const KEY='chokatsu-note-v1', $=id=>document.getElementById(id);
const options={bowel:['未記録','出なかった','出た'],shape:['未記録','コロコロ','かたい','普通','やわらかい','水っぽい'],feeling:['未記録','すっきり','ふつう','張る','痛い']};
const today=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Tokyo'}).format(new Date());
const blank=date=>({date,yogurt:false,banana:false,drink:false,water:0,bowel:'未記録',shape:'未記録',feeling:'未記録',blood:false,note:''});
const validDate=s=>typeof s==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(s)&&!isNaN(Date.parse(s))&&new Date(s).toISOString().slice(0,10)===s;
const valid=x=>x&&validDate(x.date)&&['yogurt','banana','drink','blood'].every(k=>typeof x[k]==='boolean')&&Number.isInteger(x.water)&&x.water>=0&&x.water<=30&&Object.keys(options).every(k=>options[k].includes(x[k]))&&typeof x.note==='string'&&x.note.length<=500;
let records=[],day=blank(today()),dirty=false,storageReady=false;
function message(text,error=false){$('message').textContent=text;$('message').className=error?'error':'success';}
try{const data=JSON.parse(localStorage.getItem(KEY)||'[]');if(!Array.isArray(data)||!data.every(valid))throw Error('Invalid stored records');records=data;storageReady=true;}catch(e){message('保存済みの記録を読み込めませんでした。データは変更していません。',true);$('save').disabled=true;document.querySelectorAll('#record input,#record textarea,#record button').forEach(x=>x.disabled=true);}
for(const [key,values] of Object.entries(options)){for(const value of values){const label=document.createElement('label');label.className='choice';const input=document.createElement('input');input.type='radio';input.name=key;input.value=value;label.append(input,document.createTextNode(value));input.onchange=()=>{day[key]=value;if(key==='bowel'&&value!=='出た')day.shape='未記録';changed();renderForm();};$(key).append(label);}}
function changed(){dirty=true;message('変更を保存してください');}
function renderForm(){if(!storageReady)return;$('date').value=day.date;$('date').max=today();$('date-title').textContent=new Date(day.date+'T12:00:00+09:00').toLocaleDateString('ja-JP',{month:'long',day:'numeric',weekday:'short'});$('date-sub').textContent=day.date===today()?'今日の記録':'この日の記録';$('next').disabled=day.date>=today();for(const k of ['yogurt','banana','drink','blood']){$(k).checked=day[k];if(k!=='blood')$(k).closest('label').classList.toggle('done',day[k]);}for(const k of Object.keys(options)){$(k).querySelectorAll('input').forEach(x=>{x.checked=x.value===day[k];x.closest('label').classList.toggle('selected',x.checked);});}$('shape-field').hidden=day.bowel!=='出た';$('water-count').textContent=day.water;$('water-ml').textContent=(day.water*200).toLocaleString()+' mL';$('water-progress').value=Math.min(6,day.water);$('water-remaining').textContent=day.water>=6?'✓ 1日の目安に届きました':`目安まであと${6-day.water}杯（${(6-day.water)*200}mL）`;$('water-minus').disabled=day.water===0;$('water-plus').disabled=day.water===30;$('note').value=day.note;}
function save(){if(!storageReady)return false;if(!valid(day)){message('記録の内容を確認してください',true);return false;}try{const latest=JSON.parse(localStorage.getItem(KEY)||'[]');if(!Array.isArray(latest)||!latest.every(valid))throw Error('Invalid data');const next=[{...day},...latest.filter(x=>x.date!==day.date)].sort((a,b)=>b.date.localeCompare(a.date));localStorage.setItem(KEY,JSON.stringify(next));records=next;dirty=false;message('✓ 保存しました');renderHistory();return true;}catch(e){message('保存できませんでした。入力は残しています。ブラウザの保存設定や空き容量を確認してください。',true);return false;}}
function selectDate(date){if(!validDate(date)||date>today()){renderForm();return false;}if(dirty&&!save()){renderForm();return false;}day={...(records.find(x=>x.date===date)||blank(date))};dirty=false;message('チェックがない項目は未記録です');$('message').className='muted';renderForm();return true;}
function step(n){const dt=new Date(day.date+'T12:00:00Z');dt.setUTCDate(dt.getUTCDate()+n);selectDate(dt.toISOString().slice(0,10));}
for(const key of ['yogurt','banana','drink','blood'])$(key).onchange=()=>{day[key]=$(key).checked;changed();renderForm();};$('note').oninput=()=>{day.note=$('note').value;changed();};$('water-plus').onclick=()=>{day.water=Math.min(30,day.water+1);changed();renderForm();};$('water-minus').onclick=()=>{day.water=Math.max(0,day.water-1);changed();renderForm();};$('prev').onclick=()=>step(-1);$('next').onclick=()=>step(1);$('date').onchange=e=>selectDate(e.target.value);$('save').onclick=save;
function tab(name){for(const k of ['record','history']){$(k).hidden=k!==name;$(k+'-tab').classList.toggle('active',k===name);$(k+'-tab').setAttribute('aria-selected',String(k===name));$(k+'-tab').tabIndex=k===name?0:-1;}if(name==='history')renderHistory();}
for(const k of ['record','history']){$(k+'-tab').onclick=()=>tab(k);$(k+'-tab').onkeydown=e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?'record':e.key==='End'?'history':k==='record'?'history':'record';tab(next);$(next+'-tab').focus();}};}
function node(tag,text,cls){const x=document.createElement(tag);if(text!==undefined)x.textContent=text;if(cls)x.className=cls;return x;}
function openRecord(date){if(selectDate(date)){tab('record');window.scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});}}
function renderHistory(){const week=Array.from({length:7},(_,i)=>{const dt=new Date(today()+'T12:00:00Z');dt.setUTCDate(dt.getUTCDate()-6+i);const date=dt.toISOString().slice(0,10);return{date,entry:records.find(x=>x.date===date)};});$('days-count').textContent=week.filter(x=>x.entry).length;$('bowel-count').textContent=week.filter(x=>x.entry?.bowel==='出た').length;$('week-days').replaceChildren(...week.map(({date,entry})=>{const b=node('button');b.append(node('span',Number(date.slice(-2))+'日'),node('b',entry?.bowel==='出た'?'✓':entry?'−':'·',entry?'filled':''));b.onclick=()=>openRecord(date);b.setAttribute('aria-label',date+'の記録を開く');return b;}));const list=$('history-list');list.replaceChildren();if(!records.length){const e=node('div',undefined,'card empty');e.append(node('h3','最初の1日を残そう'),node('p','保存した記録がここに並びます。'));const b=node('button','今日を記録する','text-button');b.onclick=()=>tab('record');e.append(b);list.append(e);}for(const x of records){const row=node('button',undefined,'history-row'),body=node('div');body.append(node('strong',new Date(x.date+'T12:00:00+09:00').toLocaleDateString('ja-JP',{year:'numeric',month:'long',day:'numeric',weekday:'short'})));const foods=[x.yogurt&&'ヨーグルト',x.banana&&'バナナ',x.drink&&'飲むヨーグルト',x.water>0&&`水分 ${x.water}杯`].filter(Boolean).join('・');body.append(node('p',foods||'食事・水分は未記録'),node('small',x.bowel+(x.bowel==='出た'&&x.shape!=='未記録'?' / '+x.shape:'')+' · お腹：'+x.feeling+(x.blood?' · 出血あり':'')));if(x.note)body.append(node('p',x.note,'history-note'));row.append(body,node('span','›','chev'));row.onclick=()=>openRecord(x.date);list.append(row);}$('export').disabled=!storageReady||!records.length;}
$('export').onclick=()=>{const blob=new Blob([JSON.stringify({app:'chokatsu-note',version:1,records},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='chokatsu-note-'+today()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),3000);};
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
window.addEventListener('storage',e=>{if(e.key!==KEY||dirty)return;try{const data=JSON.parse(e.newValue||'[]');if(Array.isArray(data)&&data.every(valid)){records=data;day={...(records.find(x=>x.date===day.date)||blank(day.date))};renderForm();renderHistory();}}catch{}});
if(storageReady){day={...(records.find(x=>x.date===today())||blank(today()))};renderForm();renderHistory();}
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').then(r=>r.update()).catch(()=>{});

let wallpaperURL=null;
const opacityKey='chokatsu-note-background-opacity-v1';
function applyPhotoOpacity(value){const n=Math.max(0,Math.min(100,Number(value)));$('wallpaper').style.opacity=String(n/100);$('background-opacity').value=String(n);$('background-opacity-value').textContent=n+'%';return n;}
try{const saved=localStorage.getItem(opacityKey);applyPhotoOpacity(saved!==null&&Number.isFinite(Number(saved))?Number(saved):70);}catch{applyPhotoOpacity(70);}
$('background-opacity').oninput=e=>{const n=applyPhotoOpacity(e.target.value);try{localStorage.setItem(opacityKey,String(n));}catch{$('background-status').textContent='濃さを変更しましたが、設定を保存できませんでした。';}};
function wallpaperDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open('chokatsu-note-settings',1);r.onupgradeneeded=()=>r.result.createObjectStore('photos');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.onblocked=()=>reject(Error('Database blocked'));});}
async function photoStore(action,blob){const db=await wallpaperDB();try{return await new Promise((resolve,reject)=>{const t=db.transaction('photos',action==='get'?'readonly':'readwrite'),store=t.objectStore('photos');const r=action==='get'?store.get('background'):action==='put'?store.put(blob,'background'):store.delete('background');let value;r.onsuccess=()=>{value=r.result;};t.oncomplete=()=>resolve(value);t.onerror=()=>reject(t.error);t.onabort=()=>reject(t.error||Error('Storage aborted'));});}finally{db.close();}}
function showWallpaper(blob){const previous=wallpaperURL;wallpaperURL=blob?URL.createObjectURL(blob):null;$('wallpaper').style.backgroundImage=wallpaperURL?`url("${wallpaperURL}")`:'none';document.body.classList.toggle('photo-background',!!blob);$('background-remove').disabled=!blob;if(previous)URL.revokeObjectURL(previous);}
async function loadWallpaper(){try{const blob=await photoStore('get');if(blob)showWallpaper(blob);else $('background-remove').disabled=true;}catch{$('background-status').textContent='写真の保存機能を利用できませんでした。ブラウザの保存設定を確認してください。';}}
function validatePhoto(file){return new Promise((resolve,reject)=>{const url=URL.createObjectURL(file),img=new Image();const finish=()=>URL.revokeObjectURL(url);img.onload=()=>{finish();resolve();};img.onerror=()=>{finish();reject(Error('Unsupported image'));};img.src=url;});}
$('background-file').onchange=async e=>{const file=e.target.files?.[0];if(!file)return;const input=e.target;input.disabled=true;$('background-remove').disabled=true;$('background-status').textContent='写真を保存しています…';try{if(!file.type.startsWith('image/'))throw Error('Unsupported image');await validatePhoto(file);await photoStore('put',file);showWallpaper(file);$('background-status').textContent='✓ 背景写真を保存しました。次に開いたときも表示されます。';}catch{$('background-status').textContent='写真を保存できませんでした。JPEG・PNGの写真や、小さめの画像でもう一度お試しください。';}finally{input.disabled=false;input.value='';$('background-remove').disabled=!wallpaperURL;}};
$('background-remove').onclick=async()=>{$('background-remove').disabled=true;try{await photoStore('delete');showWallpaper(null);$('background-status').textContent='背景写真を外しました。';}catch{$('background-status').textContent='写真を外せませんでした。もう一度お試しください。';$('background-remove').disabled=!wallpaperURL;}};
void loadWallpaper();

const cardOpacityKey='chokatsu-note-card-opacity-v1';
function applyCardOpacity(value){const n=Math.max(0,Math.min(100,Number(value)));document.documentElement.style.setProperty('--card-opacity',String(n/100));$('card-opacity').value=String(n);$('card-opacity-value').textContent=n+'%';return n;}
try{const saved=localStorage.getItem(cardOpacityKey);applyCardOpacity(saved!==null&&Number.isFinite(Number(saved))?Number(saved):60);}catch{applyCardOpacity(60);}
$('card-opacity').oninput=e=>{const n=applyCardOpacity(e.target.value);try{localStorage.setItem(cardOpacityKey,String(n));}catch{$('background-status').textContent='カードの濃さを変更しましたが、設定を保存できませんでした。';}};
