'use strict';
const KEY='chokatsu-note-v1', $=id=>document.getElementById(id);
const options={bowel:['未記録','出なかった','出た'],shape:['未記録','コロコロ','かたい','普通','やわらかい','水っぽい'],feeling:['未記録','すっきり','ふつう','張る','痛い']};
const today=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Tokyo'}).format(new Date());
const blank=date=>({date,yogurt:false,banana:false,drink:false,water:0,bowel:'未記録',shape:'未記録',feeling:'未記録',blood:false,note:''});
const validDate=s=>typeof s==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(s)&&!isNaN(Date.parse(s))&&new Date(s).toISOString().slice(0,10)===s;
const valid=x=>x&&validDate(x.date)&&['yogurt','banana','drink','blood'].every(k=>typeof x[k]==='boolean')&&Number.isInteger(x.water)&&x.water>=0&&x.water<=30&&Object.keys(options).every(k=>options[k].includes(x[k]))&&typeof x.note==='string'&&x.note.length<=500;
let records=[],day=blank(today()),dirty=false,storageReady=false;
function message(text,error=false){$('message').textContent=text;$('message').className=error?'error':'success';}
try{const data=JSON.parse(localStorage.getItem(KEY)||'[]');if(!Array.isArray(data)||!data.every(valid))throw Error('Invalid stored records');records=data;storageReady=true;}catch(e){message('保存済みの記録を読み込めませんでした。データは変更していません。',true);$('save').disabled=true;document.querySelectorAll('#record input,#record textarea,#record button').forEach(x=>x.disabled=true);}
for(const [key,values] of Object.entries(options)){for(const value of values){const label=document.createElement('label');label.className='choice';const input=document.createElement('input');input.type='radio';input.name=key;input.value=value;label.append(input,document.createTextNode(value));input.onchange=()=>{day[key]=value;if(key==='bowel'&&value!=='出た')day.shape='未記録';changed();renderForm();};$(key).append(label);}}
function changed(){dirty=true;message('変更を保存してください');}
function renderForm(){if(!storageReady)return;$('date').value=day.date;$('date').max=today();$('date-title').textContent=new Date(day.date+'T12:00:00+09:00').toLocaleDateString('ja-JP',{month:'long',day:'numeric',weekday:'short'});$('date-sub').textContent=day.date===today()?'今日の記録':'この日の記録';$('next').disabled=day.date>=today();for(const k of ['yogurt','banana','drink','blood']){$(k).checked=day[k];if(k!=='blood')$(k).closest('label').classList.toggle('done',day[k]);}for(const k of Object.keys(options)){$(k).querySelectorAll('input').forEach(x=>{x.checked=x.value===day[k];x.closest('label').classList.toggle('selected',x.checked);});}$('shape-field').hidden=day.bowel!=='出た';$('water-count').textContent=day.water;$('water-ml').textContent=(day.water*200).toLocaleString()+' mL';$('water-minus').disabled=day.water===0;$('water-plus').disabled=day.water===30;$('note').value=day.note;}
function save(){if(!storageReady)return false;if(!valid(day)){message('記録の内容を確認してください',true);return false;}try{const latest=JSON.parse(localStorage.getItem(KEY)||'[]');if(!Array.isArray(latest)||!latest.every(valid))throw Error('Invalid data');const next=[{...day},...latest.filter(x=>x.date!==day.date)].sort((a,b)=>b.date.localeCompare(a.date));localStorage.setItem(KEY,JSON.stringify(next));records=next;dirty=false;message('✓ 保存しました');renderHistory();return true;}catch(e){message('保存できませんでした。入力は残しています。ブラウザの保存設定や空き容量を確認してください。',true);return false;}}
function selectDate(date){if(!validDate(date)||date>today()){renderForm();return false;}if(dirty&&!save()){renderForm();return false;}day={...(records.find(x=>x.date===date)||blank(date))};dirty=false;message('チェックがない項目は未記録です');$('message').className='muted';renderForm();return true;}
function step(n){const dt=new Date(day.date+'T12:00:00Z');dt.setUTCDate(dt.getUTCDate()+n);selectDate(dt.toISOString().slice(0,10));}
for(const key of ['yogurt','banana','drink','blood'])$(key).onchange=()=>{day[key]=$(key).checked;changed();renderForm();};$('note').oninput=()=>{day.note=$('note').value;changed();};$('water-plus').onclick=()=>{day.water=Math.min(30,day.water+1);changed();renderForm();};$('water-minus').onclick=()=>{day.water=Math.max(0,day.water-1);changed();renderForm();};$('prev').onclick=()=>step(-1);$('next').onclick=()=>step(1);$('date').onchange=e=>selectDate(e.target.value);$('save').onclick=save;
function tab(name){for(const k of ['record','history']){$(k).hidden=k!==name;$(k+'-tab').classList.toggle('active',k===name);$(k+'-tab').setAttribute('aria-selected',String(k===name));$(k+'-tab').tabIndex=k===name?0:-1;}if(name==='history')renderHistory();}
for(const k of ['record','history']){$(k+'-tab').onclick=()=>tab(k);$(k+'-tab').onkeydown=e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?'record':e.key==='End'?'history':k==='record'?'history':'record';tab(next);$(next+'-tab').focus();}};}
function node(tag,text,cls){const x=document.createElement(tag);if(text!==undefined)x.textContent=text;if(cls)x.className=cls;return x;}
function openRecord(date){if(selectDate(date)){tab('record');window.scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});}}
function renderHistory(){const week=Array.from({length:7},(_,i)=>{const dt=new Date(today()+'T12:00:00Z');dt.setUTCDate(dt.getUTCDate()-6+i);const date=dt.toISOString().slice(0,10);return{date,entry:records.find(x=>x.date===date)};});$('days-count').textContent=week.filter(x=>x.entry).length;$('bowel-count').textContent=week.filter(x=>x.entry?.bowel==='出た').length;$('week-days').replaceChildren(...week.map(({date,entry})=>{const b=node('button');b.append(node('span',Number(date.slice(-2))+'日'),node('b',entry?.bowel==='出た'?'✓':entry?'−':'·',entry?'filled':''));b.onclick=()=>openRecord(date);b.setAttribute('aria-label',date+'の記録を開く');return b;}));const list=$('history-list');list.replaceChildren();if(!records.length){const e=node('div',undefined,'card empty');e.append(node('h3','最初の1日を残そう'),node('p','保存した記録がここに並びます。'));const b=node('button','今日を記録する','text-button');b.onclick=()=>tab('record');e.append(b);list.append(e);}for(const x of records){const row=node('button',undefined,'history-row'),body=node('div');body.append(node('strong',new Date(x.date+'T12:00:00+09:00').toLocaleDateString('ja-JP',{year:'numeric',month:'long',day:'numeric',weekday:'short'})));const foods=[x.yogurt&&'ヨーグルト',x.banana&&'バナナ',x.drink&&'飲むヨーグルト',x.water>0&&`水分 ${x.water}杯`].filter(Boolean).join('・');body.append(node('p',foods||'食事・水分は未記録'),node('small',x.bowel+(x.bowel==='出た'&&x.shape!=='未記録'?' / '+x.shape:'')+' · お腹：'+x.feeling+(x.blood?' · 出血あり':'')));if(x.note)body.append(node('p',x.note,'history-note'));row.append(body,node('span','›','chev'));row.onclick=()=>openRecord(x.date);list.append(row);}$('export').disabled=!storageReady||!records.length;}
$('export').onclick=()=>{const blob=new Blob([JSON.stringify({app:'chokatsu-note',version:1,records},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='chokatsu-note-'+today()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),3000);};
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
window.addEventListener('storage',e=>{if(e.key!==KEY||dirty)return;try{const data=JSON.parse(e.newValue||'[]');if(Array.isArray(data)&&data.every(valid)){records=data;day={...(records.find(x=>x.date===day.date)||blank(day.date))};renderForm();renderHistory();}}catch{}});
if(storageReady){day={...(records.find(x=>x.date===today())||blank(today()))};renderForm();renderHistory();}
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').then(r=>r.update()).catch(()=>{});
